spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rakeshallampally9600@gmail.com
    password: jmdejaouppsxsthy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/unisights
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080

storage:
  s3:
    endpoint: http://localhost:9100
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: unisights
    region: us-east-1
    presignExpireSeconds: 300

jwt:
  secret: "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890+/QWERTYUIOPASDFGHJKLZXCVBNM="
