spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/unisights?serverTimezone=UTC&useTimezone=true&useLegacyDatetimeCode=false
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
server:
  port: 8080
