management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
