name: Deploy Staging

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ghcr.io/unisights/unisights-backend:staging
          docker push ghcr.io/unisights/unisights-backend:staging

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy to Staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /opt/unisights
            docker compose -f docker-compose.staging.yml --env-file .env.staging pull backend
            docker compose -f docker-compose.staging.yml --env-file .env.staging up -d
