# YAML
name: Deploy Staging

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t docker.io/rakeshallampally960/unisights-backend:staging .
          docker push docker.io/rakeshallampally960/unisights-backend:staging

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy with Docker Compose on server
        run: |
          cd /opt/unisights
          docker compose -f docker-compose.staging.yml --env-file .env.staging pull backend
          docker compose -f docker-compose.staging.yml --env-file .env.staging up -d
